# TANAW Global Configuration
# Phase 0: Global config & conventions

# File Processing Configuration
MAX_FILE_SIZE_MB: 50
SAMPLE_ROWS_LIMIT: 1000
SAMPLE_MIN: 50

# Column Mapping Configuration
AUTO_MAP_CONF: 0.90
SUGGEST_CONF_MIN: 0.70
GPT_ESCALATE_CONF: 0.70

# GPT Configuration
GPT_MODEL_DEFAULT: "gpt-4o-mini"
GPT_FALLBACK_MODEL: "gpt-4o"
GPT_MAX_TOKENS: 500
GPT_TIMEOUT_SEC: 20
GPT_MAX_RETRIES: 3

# Database Configuration
KB_DB: "mongodb://localhost:27017/tanaw_kb"
CACHE_TTL_SEC: 3600

# Processing Configuration
MAX_COLUMNS_PER_GPT: 10
ENCODING_FALLBACKS: ["utf-8", "utf-16", "latin-1", "cp1252"]

# Feature Flags
ENABLE_GPT: true
ENABLE_CACHING: true
ENABLE_LEARNING: true
ENABLE_CROSS_USER_LEARNING: false

# Security Configuration
FLASK_SECRET_KEY: "dev-secret-key-change-in-production"
ALLOWED_ORIGINS: ["http://localhost:3000", "http://localhost:5000"]
RATE_LIMIT_PER_MINUTE: 60

# Environment
ENVIRONMENT: "development"
LOG_LEVEL: "INFO"
